version: 2
updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: dev  # Se mantiene dev como rama objetivo
    schedule:
      interval: monthly

  - package-ecosystem: npm
    labels: []
    directory: /
    target-branch: dev  # Se mantiene dev como rama objetivo
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    labels: []
    directory: /
    target-branch: dev  # Se mantiene dev como rama objetivo
    schedule:
      interval: monthly