blank_issues_enabled: false
contact_links:
  - name: ðŸ—¨ Discussions
    url: https://github.com/cupul-miu-04/revoid-library/discussions
    about: Have something unspecific to ReVoid Library in mind? Search for or start a new discussion!