name: Open a PR to master  # CAMBIADO: de main a master

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  MESSAGE: Merge branch `${{ github.head_ref || github.ref_name }}` to `master`  # CAMBIADO: main → master

jobs:
  pull-request:
    name: Open pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Open pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'master'  # CAMBIADO: main → master
          pr_title: 'chore: ${{ env.MESSAGE }}'
          pr_body: 'This pull request will ${{ env.MESSAGE }}.'
          pr_draft: true